let cau_noi_hay = [
    "Học, học nữa, học mãi. - Hồ Chí Minh",
    "Học không bao giờ là đủ. - Khuyết danh",
    "Trí tuệ không phải sản phẩm của trường lớp, mà là kết quả của nỗ lực học hỏi suốt đời. - Albert Einstein",
    "Con đường đến thành công là con đường của sự học tập, sự phát triển và không ngừng cố gắng. - Oprah Winfrey",
    "Học là một hành trình, không phải là đích đến. - Khuyết danh",
    "Học để biết, học để làm, học để chung sống, học để tự khẳng định mình. - UNESCO",
    "Học không phải là học thuộc lòng sự thật, mà là rèn luyện tư duy để suy nghĩ. - Albert Einstein",
    "Hãy là chính mình, những người khác đã là người khác rồi. - Oscar Wilde",
    "Bạn chính là người định nghĩa cuộc đời mình. Đừng để người khác viết kịch bản cho bạn. - Oprah Winfrey",
    "Điều nằm phía sau và phía trước chúng ta chỉ là chuyện nhỏ so với điều nằm bên trong chúng ta. - Ralph Waldo Emerson",
    "Không sợ bạn đi chậm, chỉ sợ bạn đứng yên. - Khuyết danh",
    "Lúc nhỏ, người ta nhìn bố mẹ để đánh giá bạn. Lớn lên, người ta nhìn vào lượng công nghệ bạn biết để nhờ bạn sửa hộ điện thoại cho bố mẹ bạn.",
    "Sự hiện diện của bạn có thể mang lại hạnh phúc cho người khác. Tôi hy vọng bạn sẽ nhớ kỹ điều đó. - World Wide Handsome",
    "Đôi khi, nhìn bạn bè tiến lên phía trước khiến tôi cảm thấy lo lắng... nhưng tôi nhanh chóng nhận ra rằng tốc độ của họ không phải là tốc độ của tôi. Mỗi khi điều đó xảy ra, điều giúp tôi tiếp tục tiến lên chính là lời hứa với bản thân rằng 'cứ từ từ thôi'. - Jin (BTS, hay còn gọi là World Wide Handsome)",
    "Nhưng tôi tin rằng ngay cả những thứ vô dụng cũng có mục đích! Tôi nghĩ chúng ta cần những ngày mà người khác cho là lãng phí để sau này có thể tập trung vào những việc hữu ích hơn. - Jin (BTS)",
    "FACT: Bạn có biết, RM (BTS) đã tự học tiếng Anh bằng cách nghe nhạc Mỹ và xem phim Hollywood? Điều này chứng tỏ rằng việc học không nhất thiết phải diễn ra trong một lớp học truyền thống.",
    "Sống mà không có đam mê cũng giống như chết. - Jungkook (Đã sửa lại)",
    "Nỗ lực tạo nên con người bạn. Nếu bạn không cố gắng hết sức ngay bây giờ, bạn sẽ hối hận vào một ngày nào đó. Đừng nghĩ rằng đã quá muộn; hãy tiếp tục cố gắng. Cho dù mất thời gian, việc luyện tập sẽ giúp mọi thứ tốt hơn. - Jungkook (Em út vàng)",
    "Đừng bao giờ từ bỏ ước mơ của bạn. Hãy tiếp tục cố gắng, và một ngày nào đó, bạn sẽ đạt được những điều tuyệt vời. - V (BTS)",
    "Những ai không có ước mơ thì cũng không sao. Không sao cả nếu bạn không có ước mơ. Điều quan trọng là bạn phải hạnh phúc. - Suga (BTS)",
    "No matter how hard it is right now, think of how the result will make you feel. - Jimin (BTS)",
    "Your time is limited, so don't waste it living someone else's life. - Steve Jobs",
    "Love myself, love my fans, love my music. That’s all that matters. - Idol nào đó",
    "Bản thân việc học là một quá trình tự khám phá, chứ không phải là sự áp đặt từ bên ngoài. - Noam Chomsky",
    "Rễ của giáo dục thì đắng cay, nhưng quả của nó lại ngọt ngào. - Aristotle",
    "Giáo dục là vũ khí mạnh nhất mà bạn có thể sử dụng để thay đổi thế giới. - Nelson Mandela",
    "Học không phải là việc lấp đầy một cái xô, mà là thắp sáng một ngọn lửa. - Plutarch",
    "Hãy sống như hoa dại, dù khắc nhiệt nhưng kiên cường - Khuyết danh",
    "Chỉ cần thay đổi góc nhìn, bạn sẽ thấy cả thế giới khác đi. - Khuyết danh",
    "Đừng bao giờ đánh giá thấp sức mạnh của một nụ cười. - Khuyết danh",
    "Bạn không cần phải ao ước cuộc sống của người khác, bởi mỗi người đều có ánh dương chiếu rọi, mỗi người đều có ánh hào quang 'độc nhất vô nhị' của bản thân.",
    "Chúng ta không thể đánh vần chữ L-O-V-E mà không có ‘V’ - V (BTS)",
    "Bạn không thể bước vào cuộc đời của một ai đó, khiến họ cảm thấy đặc biệt, rồi rời đi. - V (BTS)",
    "Khi mọi thứ trở nên khó khăn, hãy dừng lại một chút và nhìn lại xem bạn đã đi được bao xa. Đừng quên nó đáng giá như thế nào. Bạn là bông hoa đẹp nhất, hơn bất kỳ ai khác trên thế giới này. - V (BTS)",
    "Cuộc sống là một tác phẩm điêu khắc mà bạn tạo ra khi bạn mắc sai lầm và học hỏi từ chúng. - BTS",
    "Hãy là chính mình, những người khác đã có người khác rồi. - Oscar Wilde",
];