let cau_noi_hay = [
    "Học, học nữa, học mãi. - Hồ Chí Minh",
    "Học không bao giờ là đủ. - Khuyết danh",
    "Trí tuệ không phải sản phẩm của trường lớp, mà là kết quả của nỗ lực học hỏi suốt đời. - Albert Einstein",
    "Con đường đến thành công là con đường của sự học tập, sự phát triển và không ngừng cố gắng. - Oprah Winfrey",
    "Học là một hành trình, không phải là đích đến. - Khuyết danh",
    "Học để biết, học để làm, học để chung sống, học để tự khẳng định mình. - UNESCO",
    "Học không phải là học thuộc lòng sự thật, mà là rèn luyện tư duy để suy nghĩ. - Albert Einstein",
    "Hãy là chính mình, những người khác đã là người khác rồi. - Oscar Wilde",
    "Bạn chính là người định nghĩa cuộc đời mình. Đừng để người khác viết kịch bản cho bạn. - Oprah Winfrey",
    "Điều nằm phía sau và phía trước chúng ta chỉ là chuyện nhỏ so với điều nằm bên trong chúng ta. - Ralph Waldo Emerson",
    "Không sợ bạn đi chậm, chỉ sợ bạn đứng yên. - Khuyết danh",
    "Khi bạn còn nhỏ, sự yêu thương của bố mẹ là lá chắn bảo vệ bạn. Khi bạn lớn lên, sự vững vàng của bạn là chỗ dựa bình yên cho bố mẹ",
    "Sự hiện diện của bạn có thể mang lại hạnh phúc cho người khác. Tôi hy vọng bạn sẽ nhớ kỹ điều đó. - World Wide Handsome",
    "Đôi khi, nhìn bạn bè tiến lên phía trước khiến tôi cảm thấy lo lắng... nhưng tôi nhanh chóng nhận ra rằng tốc độ của họ không phải là tốc độ của tôi. Mỗi khi điều đó xảy ra, điều giúp tôi tiếp tục tiến lên chính là lời hứa với bản thân rằng 'cứ từ từ thôi'. - Jin (BTS, hay còn gọi là World Wide Handsome)",
    "Nhưng tôi tin rằng ngay cả những thứ vô dụng cũng có mục đích! Tôi nghĩ chúng ta cần những ngày mà người khác cho là lãng phí để sau này có thể tập trung vào những việc hữu ích hơn. - Jin (BTS)",
    "FACT: Bạn có biết, RM (BTS) đã tự học tiếng Anh bằng cách nghe nhạc Mỹ và xem phim Hollywood? Điều này chứng tỏ rằng việc học không nhất thiết phải diễn ra trong một lớp học truyền thống.",
    "Sống mà không có đam mê cũng giống như chết. - Jungkook (Đã sửa lại)",
    "Nỗ lực tạo nên con người bạn. Nếu bạn không cố gắng hết sức ngay bây giờ, bạn sẽ hối hận vào một ngày nào đó. Đừng nghĩ rằng đã quá muộn; hãy tiếp tục cố gắng. Cho dù mất thời gian, việc luyện tập sẽ giúp mọi thứ tốt hơn. - Jungkook (Em út vàng)",
    "Đừng bao giờ từ bỏ ước mơ của bạn. Hãy tiếp tục cố gắng, và một ngày nào đó, bạn sẽ đạt được những điều tuyệt vời. - V (BTS)",
    "Những ai không có ước mơ thì cũng không sao. Không sao cả nếu bạn không có ước mơ. Điều quan trọng là bạn phải hạnh phúc. - Suga (BTS)",
    "No matter how hard it is right now, think of how the result will make you feel. - Jimin (BTS)",
    "Your time is limited, so don't waste it living someone else's life. - Steve Jobs",
    "Love myself, love my fans, love my music. That’s all that matters. - Min Yoongi (Suga - BTS)",
    "Bản thân việc học là một quá trình tự khám phá, chứ không phải là sự áp đặt từ bên ngoài. - Noam Chomsky",
    "Rễ của giáo dục thì đắng cay, nhưng quả của nó lại ngọt ngào. - Aristotle",
    "Giáo dục là vũ khí mạnh nhất mà bạn có thể sử dụng để thay đổi thế giới. - Nelson Mandela",
    "Học không phải là việc lấp đầy một cái xô, mà là thắp sáng một ngọn lửa. - Plutarch",
    "Hãy sống như hoa dại, dù khắc nhiệt nhưng kiên cường - Khuyết danh",
    "Chỉ cần thay đổi góc nhìn, bạn sẽ thấy cả thế giới khác đi. - Khuyết danh",
    "Đừng bao giờ đánh giá thấp sức mạnh của một nụ cười. - Khuyết danh",
    "Bạn không cần phải ao ước cuộc sống của người khác, bởi mỗi người đều có ánh dương chiếu rọi, mỗi người đều có ánh hào quang 'độc nhất vô nhị' của bản thân.",
    "Chúng ta không thể đánh vần chữ L-O-V-E mà không có ‘V’ - V (BTS)",
    "Bạn không thể bước vào cuộc đời của một ai đó, khiến họ cảm thấy đặc biệt, rồi rời đi. - V (BTS)",
    "Khi mọi thứ trở nên khó khăn, hãy dừng lại một chút và nhìn lại xem bạn đã đi được bao xa. Đừng quên nó đáng giá như thế nào. Bạn là bông hoa đẹp nhất, hơn bất kỳ ai khác trên thế giới này. - V (BTS)",
    "Cuộc sống là một tác phẩm điêu khắc mà bạn tạo ra khi bạn mắc sai lầm và học hỏi từ chúng. - BTS",
    "Hãy là chính mình, những người khác đã có người khác rồi. - Oscar Wilde",
    "Không có định nghĩa nào cho sự hoàn hảo cả, bạn chính là người tự đặt ra tiêu chuẩn cho riêng mình. - RM (BTS)",
    "Nếu bạn không thể bay, hãy chạy. Nếu không thể chạy, hãy đi bộ. Hôm nay chúng ta bước đi, ngày mai chúng ta sẽ chạy. - Martin Luther King Jr.",
    "Thất bại là mẹ của thành công - Thành ngữ Việt Nam",
    "Bất luận ngày mai có ra sao, việc của bạn hôm nay chính là nỗ lực tích lũy năng lượng, để bản thân có đủ tư cách lựa chọn cuộc sống mình mong muốn. - Khuyết danh",
    "Giá trị của bạn không nằm ở việc bạn đứng thứ mấy trong lớp, mà nằm ở việc bạn có dám đứng lên sau mỗi lần vấp ngã hay không. - Khuyết danh",
    "Tôi chưa từng thất bại. Tôi chỉ là đã tìm ra 10.000 cách không hoạt động. - Thomas Edison",
    "Nhà trường cho chúng ta bài học trước rồi mới kiểm tra. Cuộc đời bắt chúng ta kiểm tra trước rồi mới rút ra bài học. - Tom Bodett",
    "Đừng bao giờ cúi đầu. Hãy luôn ngẩng cao. Nhìn thẳng vào mắt thế giới. - Helen Keller",
    "Đời người phải trải qua giông tố nhưng không được cúi đầu trước giông tố. - BS.Đặng Thùy Trâm",
    "Giữa những ngày rực lửa này, mình vẫn thấy lòng mình trong sáng và tràn đầy niềm tin... Niềm tin ấy là sức mạnh giúp mình vượt qua tất cả. - BS.Đặng Thùy Trâm",
    "Ta chưa từng thấy ai không giữ được lòng liêm khiết mà có thể dạy người khác thành bậc chính nhân quân tử - Chu Văn An",
    "Đừng lo lắng về những gì người khác nói. Hãy tin vào chính mình và làm những gì bạn muốn. Tương lai của bạn nằm trong tay bạn chứ không phải ai khác - J-hope (BTS)",
    "Đừng hối hận vì những gì đã qua trong quá khứ. Hãy lấy nó làm bài học để tạo nên một tương lai tốt đẹp hơn - Golden Maknae",
    "Tôi chỉ có hai quy tắc: Làm tất cả những gì bạn có thể và làm tốt nhất có thể. Đó là cách duy nhất để bạn cảm thấy tự hào về bản thân - Ông KFC (Đại tá Sanders)",
    "Tôi không biết thế giới nhìn nhận mình thế nào, nhưng đối với chính mình, tôi chỉ là một cậu bé đang chơi trên bờ biển, thỉnh thoảng tìm được một viên sỏi nhẵn hơn hay một vỏ sò đẹp hơn... trong khi đại dương chân lý vĩ đại vẫn còn ẩn giấu trước mắt. - Isaac Newton",
    "Nếu muốn ngồi ở nơi không ai ngồi được, thì phải chịu được những cảm giác không ai chịu được. - Sơn Tùng M-TP (Đã sửa lại)",
    "Dù có bị từ chối 100 lần, tôi vẫn sẽ tiếp tục thử lần thứ 101. Tôi chưa bao giờ từ bỏ ước mơ diễn xuất, ngay cả trong những lúc khó khăn nhất. - Byeon Woo Seok (Nam diễn viên Hàn Quốc từng bị từ chối 100 lần suốt 9 năm trước khi nổi tiếng)",
    "Bạn không cần phải hoàn hảo để được yêu thương. Chỉ cần là chính mình, với tất cả những khiếm khuyết, bạn đã là một phiên bản tuyệt vời nhất rồi - IU (Nữ hoàng K-pop)",
    "Người duy nhất tôi cần phải vượt qua chính là bản thân tôi của ngày hôm qua. - G-Dragon",
    "Tôi đã làm được, bạn cũng có thể làm được. - H'Hen Niê",
    "Tôi luôn muốn thể hiện những khía cạnh khác nhau của bản thân. - Kim Bum",
    "Phát ngôn ra một lời nói rất dễ, nhưng biết khi nào cần im lặng để lắng nghe, để thấu hiểu và để không gây tổn thương cho người khác lại là bài học lớn nhất của một đời người. - Ernest Hemingway",
    "Tuổi tác thật sự của một con người không đo bằng số năm họ sống trên đời, mà đo bằng ngọn lửa nhiệt huyết và lý tưởng trong trái tim họ. - Gabriel García Márquez",
    "Cách tốt nhất để bắt đầu là ngừng nói và hãy bắt tay vào làm - Walt Disney",
    "Bạn không cần phải giỏi mới được bắt đầu, nhưng bạn phải bắt đầu thì mới giỏi được. - Zig Ziglar",
    "Cuộc sống không phải là chờ đợi cơn bão đi qua, mà là học cách nhảy múa trong mưa - Vivian Greene",
    "Trưởng thành là khi ta nhận ra, thế giới này không xoay quanh mình, và cũng chẳng có ai thực sự đứng đợi ta ở cuối con đường - Ai đó",
    "Dù có chuyện gì xảy ra đi chăng nữa, tôi vẫn luôn tin rằng bản thân mình đã làm hết sức có thể. Nếu kết quả không như ý, thì ít nhất tôi cũng không có gì phải hối tiếc vì đã không buông bỏ - Lee Dong-wook",
    "Hãy cứ chậm lại một chút. Thế giới này vận hành quá nhanh, nhưng điều đó không có nghĩa là bạn cũng phải vội vã đánh mất bản thân mình. - Lee Dong-wook",
    "Việc chăm sóc bản thân không chỉ là vẻ bề ngoài, đó là cách bạn tôn trọng chính hành trình mình đang đi. - Kim Bum",
    "Hạnh phúc không phải là thứ bạn phải đạt được. Bạn có thể cảm thấy hạnh phúc ngay trong quá trình tiến đến mục tiêu của mình - Kim Nam Joon (RM của BTS)",
    "Khi bạn gặp phải khó khăn, hãy biến nó thành động lực. Đừng bao giờ chọn con đường dễ dàng nhất, hãy chọn con đường giúp bạn học hỏi được nhiều nhất. - Elon Musk",
    "FACT: Một ngày não bộ của bạn tạo ra khoảng 70.000 suy nghĩ. Nếu bạn dùng suy nghĩ đó để làm việc thay vì chỉ lo âu, bạn đã có thể làm được khối việc rồi!",
    "Your best is enough - Corgi",
    "Hãy tự viết lên câu nói của bạn - App Học Tập",
    "Hãy nói theo cách riêng của bạn - Viettel",
    "FACT: Steve Jobs, lúc cho ra mắt điện thoại cảm ứng, ai cũng nghĩ nó là điên rồ và bất khả thi. Nhưng sau hơn 20 năm, cả thế giới vẫn đang dùng nó.",
    "FACT: Thuở nhỏ ở vùng quê nghèo Madeira, gia đình Ronaldo nghèo đến mức không có tiền mua nổi một quả bóng tử tế. Anh chàng toàn phải gom giẻ lau, tất cũ cuộn lại thành hình tròn để đá.",
    "FACT: Năm 11 tuổi, Messi đối mặt với cú sốc lớn nhất đời: anh bị chẩn đoán mắc chứng thiếu hụt hormone tăng trưởng. Nếu không chữa trị, Messi sẽ chỉ cao tối đa khoảng 1m40 và vĩnh viễn không thể chơi bóng chuyên nghiệp. Chi phí chữa trị lên tới $900/tháng, một con số không tưởng với gia đình anh lúc bấy giờ. Để tiếp tục đam mê, Messi đã phải trải qua một cuộc chiến thể xác cực kỳ tàn nhẫn đối với một đứa trẻ. Suốt 3 năm trời, mỗi buổi tối trước khi đi ngủ, Messi phải tự tay đâm kim tiêm hormone vào chân mình. Anh từng chia sẻ: 'Ban đầu là một chân, sau đó là chân kia. Nó đau đớn, nhưng tôi không khóc, vì tôi biết đó là cách duy nhất để tôi có thể tiếp tục chơi bóng'. Sự kiên trì và chịu đựng của Messi năm 11 tuổi là nền móng tạo nên một 'vua lỳ đòn' trên sân cỏ sau này."
];